# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from server import server_pb2 as server__pb2


class DigitalWatermarkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encrypt = channel.unary_unary(
                '/server.DigitalWatermark/Encrypt',
                request_serializer=server__pb2.EncryptAction.SerializeToString,
                response_deserializer=server__pb2.EncryptResponse.FromString,
                )
        self.Decrypt = channel.unary_unary(
                '/server.DigitalWatermark/Decrypt',
                request_serializer=server__pb2.DecryptAction.SerializeToString,
                response_deserializer=server__pb2.DecryptResponse.FromString,
                )


class DigitalWatermarkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Encrypt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrypt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigitalWatermarkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Encrypt,
                    request_deserializer=server__pb2.EncryptAction.FromString,
                    response_serializer=server__pb2.EncryptResponse.SerializeToString,
            ),
            'Decrypt': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrypt,
                    request_deserializer=server__pb2.DecryptAction.FromString,
                    response_serializer=server__pb2.DecryptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.DigitalWatermark', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DigitalWatermark(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Encrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.DigitalWatermark/Encrypt',
            server__pb2.EncryptAction.SerializeToString,
            server__pb2.EncryptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decrypt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.DigitalWatermark/Decrypt',
            server__pb2.DecryptAction.SerializeToString,
            server__pb2.DecryptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
