# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\",\n\rEncryptAction\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\x0e\n\x06secret\x18\x02 \x01(\x0c\"2\n\x0f\x45ncryptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\x0c\"\x1c\n\rDecryptAction\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"2\n\x0f\x44\x65\x63ryptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\x0c\x32\x88\x01\n\x10\x44igitalWatermark\x12\x39\n\x07\x45ncrypt\x12\x15.server.EncryptAction\x1a\x17.server.EncryptResponse\x12\x39\n\x07\x44\x65\x63rypt\x12\x15.server.DecryptAction\x1a\x17.server.DecryptResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCRYPTACTION._serialized_start=24
  _ENCRYPTACTION._serialized_end=68
  _ENCRYPTRESPONSE._serialized_start=70
  _ENCRYPTRESPONSE._serialized_end=120
  _DECRYPTACTION._serialized_start=122
  _DECRYPTACTION._serialized_end=150
  _DECRYPTRESPONSE._serialized_start=152
  _DECRYPTRESPONSE._serialized_end=202
  _DIGITALWATERMARK._serialized_start=205
  _DIGITALWATERMARK._serialized_end=341
# @@protoc_insertion_point(module_scope)
